import type { FilingTable } from "../sec/filing-text";
import { parseAmount } from "../sec/units";

// How a statement is shown to an extraction agent, and how its answers are
// turned back into numbers.
//
// The split of work is deliberate. Reading row labels is judgment - "Cash
// generated by operating activities", "Net cash (used in)/provided by...",
// "Consolidated net income attributable to Walmart" all mean specific
// things - so that's the model's job: pick the row. Which column is this
// year, what unit the figures are in, and what a parenthesized number means
// are facts about the page, so code does those and never asks.

// Rows as the agent sees them: "R12: Total assets | 359,241 | 364,980".
export function renderForAgent(table: FilingTable): string {
  return table.rows.map((r, i) => `R${i}: ${r.join(" | ")}`).join("\n");
}

function isYear(cell: string): boolean {
  return /^(fiscal\s*)?(19|20)\d{2}$/i.test(cell.trim());
}

// The column holding the current period. Statements label their columns
// by year, current year first in almost every 10-K, but not all - so the
// header row is read rather than assumed. A fiscal year is labeled with the
// calendar year it ends in (Walmart's year ending January 2026 is "2026"),
// so the period end's year identifies the column.
export function currentPeriodColumn(
  table: FilingTable,
  periodEnd: string,
): number {
  const year = periodEnd.slice(0, 4);
  for (const row of table.rows.slice(0, 12)) {
    const years = row.filter(isYear);
    if (years.length >= 2) {
      const idx = years.findIndex((c) => c.includes(year));
      if (idx !== -1) return idx;
    }
  }
  return 0;
}

// The printed figure in a row's current-period column. Data rows list their
// figures after the label, one per period, so the column index counts
// figures, not raw cells. A row whose first cell is already a figure has no
// label (Merck prints some totals that way).
export function figureAt(row: string[], column: number): string | null {
  const labeled = parseAmount(row[0]) === null;
  const figures = (labeled ? row.slice(1) : row).filter(
    (c) => parseAmount(c) !== null || /^[-\u2014\u2013]$/.test(c),
  );
  return figures[column] ?? null;
}

export function sameFigure(a: string, b: string): boolean {
  const x = parseAmount(a);
  const y = parseAmount(b);
  return x !== null && y !== null && Math.abs(Math.abs(x) - Math.abs(y)) < 1e-9;
}
