import type { FilingTable } from "../sec/filing-text";
import { parseAmount } from "../sec/units";

// How a statement is shown to an extraction agent, and how its answers are
// turned back into numbers.
//
// The split of work is deliberate. Reading row labels is judgment - "Cash
// generated by operating activities", "Net cash (used in)/provided by...",
// "Consolidated net income attributable to Walmart" all mean specific
// things - so that's the model's job: pick the row. Which column is this
// year, what unit the figures are in, and what a parenthesized number means
// are facts about the page, so code does those and never asks.

// Rows as the agent sees them: "R12: Total assets | 359,241 | 364,980".
export function renderForAgent(table: FilingTable): string {
  return table.rows.map((r, i) => `R${i}: ${r.join(" | ")}`).join("\n");
}

// Column headers name the period as a bare year ("2025"), a fiscal year
// ("Fiscal 2026"), or a phrase ending in the period-end date ("September
// 27, 2025", "Years ended December 31, 2025", "AtDecember 31, 2025"). Each
// is words, maybe a day of the month, then the year - and the year is what
// identifies the column.
const PERIOD_HEADER =
  /^[a-z][a-z .,]*?(?:\d{1,2},?\s*)?((?:19|20)\d{2})$|^((?:19|20)\d{2})$/i;

function headerYear(cell: string): string | null {
  const m = cell.trim().match(PERIOD_HEADER);
  return m ? (m[1] ?? m[2]) : null;
}

// The current- and prior-period columns. Statements label columns by year,
// current year first in almost every 10-K but not all, so the header row
// is read rather than assumed. Two labeling conventions exist for fiscal
// years that end early in a calendar year: Walmart calls its year ending
// January 2026 "2026", while Home Depot and Target call theirs "Fiscal
// 2025". So the header decides: if the period-end year appears, labels
// follow the end year; if only earlier years do, labels run one behind.
export function periodColumns(
  table: FilingTable,
  periodEnd: string,
): { current: number; prior: number | null } {
  const endYear = Number(periodEnd.slice(0, 4));
  for (const row of table.rows.slice(0, 12)) {
    const years = row.map(headerYear).filter((y): y is string => y !== null);
    if (years.length < 2) continue;
    const label = years.includes(String(endYear))
      ? endYear
      : years.includes(String(endYear - 1))
        ? endYear - 1
        : null;
    if (label === null) continue;
    const current = years.indexOf(String(label));
    const prior = years.indexOf(String(label - 1));
    return { current, prior: prior === -1 ? null : prior };
  }
  return { current: 0, prior: null };
}

export function currentPeriodColumn(
  table: FilingTable,
  periodEnd: string,
): number {
  return periodColumns(table, periodEnd).current;
}

export function priorPeriodColumn(
  table: FilingTable,
  periodEnd: string,
): number | null {
  return periodColumns(table, periodEnd).prior;
}

// The printed figure in a row's current-period column. Data rows list their
// figures after the label, one per period, so the column index counts
// figures, not raw cells. A row whose first cell is already a figure has no
// label (Merck prints some totals that way).
export function figureAt(row: string[], column: number): string | null {
  const labeled = parseAmount(row[0]) === null;
  const figures = (labeled ? row.slice(1) : row).filter(
    (c) => parseAmount(c) !== null || /^[-\u2014\u2013]$/.test(c),
  );
  return figures[column] ?? null;
}

export function sameFigure(a: string, b: string): boolean {
  const x = parseAmount(a);
  const y = parseAmount(b);
  return x !== null && y !== null && Math.abs(Math.abs(x) - Math.abs(y)) < 1e-9;
}

// Rows that print no figure in the current column are section headers
// ("Net earnings (loss) per share:"). A figure row belongs to the nearest
// header above it.
export function headerAbove(
  table: FilingTable,
  row: number,
  column: number,
): string {
  for (let i = row - 1; i >= 0; i--) {
    if (figureAt(table.rows[i], column) === null) return table.rows[i][0];
  }
  return "";
}

function normalizeLabel(s: string): string {
  return s
    .toLowerCase()
    .replace(/\((?:[a-z]|\d{1,2}|note \d+[^)]*)\)/g, "") // footnote markers
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

// What identifies "the same line" in two different years' statements: its
// label, qualified by its section header, since labels repeat (Duke prints
// "Basic and Diluted" under both continuing operations and net income).
// Unlabeled total rows are identified by their position among unlabeled
// rows instead, since they have no label to match.
export function rowKey(
  table: FilingTable,
  row: number,
  column: number,
): string {
  const label = table.rows[row][0];
  if (parseAmount(label) !== null) {
    const nth = table.rows
      .slice(0, row + 1)
      .filter((r) => parseAmount(r[0]) !== null).length;
    return `unlabeled#${nth}`;
  }
  return `${normalizeLabel(headerAbove(table, row, column))} | ${normalizeLabel(label)}`;
}
